version: "3"
services:
  es1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - "9201:9200"
    volumes:
      - ./es1:/usr/share/elasticsearch/data
    environment:
      - node.name=es1
      - node.master=true
      - node.data=false
      - node.ingest=false
      - node.remote_cluster_client=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.seed_hosts=es2,es3,es4
      - cluster.initial_master_nodes=es1
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - "9202:9200"
    volumes:
      - ./es2:/usr/share/elasticsearch/data
    environment:
      - node.name=es2
      - node.master=false
      - node.data=true
      - node.ingest=true
      - node.remote_cluster_client=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.seed_hosts=es1
      - xpack.monitoring.collection.enabled=true
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - "9203:9200"
    volumes:
      - ./es3:/usr/share/elasticsearch/data
    environment:
      - node.name=es3
      - node.master=false
      - node.data=true
      - node.ingest=true
      - node.remote_cluster_client=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.seed_hosts=es1
      - xpack.monitoring.collection.enabled=true
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es4:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - "9204:9200"
    volumes:
      - ./es4:/usr/share/elasticsearch/data
    environment:
      - node.name=es4
      - node.master=false
      - node.data=true
      - node.ingest=true
      - node.remote_cluster_client=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.seed_hosts=es1
      - xpack.monitoring.collection.enabled=true
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOSTS: http://es1:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
